export const weatherDescription: { [key: string]: string } = {
  clearsky_day: 'Clear Sky (Day)',
  clearsky_night: 'Clear Sky (Night)',
  clearsky_polartwilight: 'Clear Sky (Polar Twilight)',
  fair_day: 'Fair (Day)',
  fair_night: 'Fair (Night)',
  fair_polartwilight: 'Fair (Polar Twilight)',
  partlycloudy_day: 'Partly Cloudy (Day)',
  partlycloudy_night: 'Partly Cloudy (Night)',
  partlycloudy_polartwilight: 'Partly Cloudy (Polar Twilight)',
  cloudy: 'Cloudy',
  rainshowers_day: 'Rain Showers (Day)',
  rainshowers_night: 'Rain Showers (Night)',
  rainshowers_polartwilight: 'Rain Showers (Polar Twilight)',
  rainshowersandthunder_day: 'Rain Showers with Thunder (Day)',
  rainshowersandthunder_night: 'Rain Showers with Thunder (Night)',
  rainshowersandthunder_polartwilight: 'Rain Showers with Thunder (Polar Twilight)',
  sleetshowers_day: 'Sleet Showers (Day)',
  sleetshowers_night: 'Sleet Showers (Night)',
  sleetshowers_polartwilight: 'Sleet Showers (Polar Twilight)',
  snowshowers_day: 'Snow Showers (Day)',
  snowshowers_night: 'Snow Showers (Night)',
  snowshowers_polartwilight: 'Snow Showers (Polar Twilight)',
  rain: 'Rain',
  heavyrain: 'Heavy Rain',
  heavyrainandthunder: 'Heavy Rain with Thunder',
  sleet: 'Sleet',
  snow: 'Snow',
  snowandthunder: 'Snow with Thunder',
  fog: 'Fog',
  sleetshowersandthunder_day: 'Sleet Showers with Thunder (Day)',
  sleetshowersandthunder_night: 'Sleet Showers with Thunder (Night)',
  sleetshowersandthunder_polartwilight: 'Sleet Showers with Thunder (Polar Twilight)',
  snowshowersandthunder_day: 'Snow Showers with Thunder (Day)',
  snowshowersandthunder_night: 'Snow Showers with Thunder (Night)',
  snowshowersandthunder_polartwilight: 'Snow Showers with Thunder (Polar Twilight)',
  rainandthunder: 'Rain with Thunder',
  sleetandthunder: 'Sleet with Thunder',
  lightrainshowersandthunder_day: 'Light Rain Showers with Thunder (Day)',
  lightrainshowersandthunder_night: 'Light Rain Showers with Thunder (Night)',
  lightrainshowersandthunder_polartwilight: 'Light Rain Showers with Thunder (Polar Twilight)',
  heavyrainshowersandthunder_day: 'Heavy Rain Showers with Thunder (Day)',
  heavyrainshowersandthunder_night: 'Heavy Rain Showers with Thunder (Night)',
  heavyrainshowersandthunder_polartwilight: 'Heavy Rain Showers with Thunder (Polar Twilight)',
  lightssleetshowersandthunder_day: 'Light Sleet Showers with Thunder (Day)',
  lightssleetshowersandthunder_night: 'Light Sleet Showers with Thunder (Night)',
  lightssleetshowersandthunder_polartwilight: 'Light Sleet Showers with Thunder (Polar Twilight)',
  heavysleetshowersandthunder_day: 'Heavy Sleet Showers with Thunder (Day)',
  heavysleetshowersandthunder_night: 'Heavy Sleet Showers with Thunder (Night)',
  heavysleetshowersandthunder_polartwilight: 'Heavy Sleet Showers with Thunder (Polar Twilight)',
  lightssnowshowersandthunder_day: 'Light Snow Showers with Thunder (Day)',
  lightssnowshowersandthunder_night: 'Light Snow Showers with Thunder (Night)',
  lightssnowshowersandthunder_polartwilight: 'Light Snow Showers with Thunder (Polar Twilight)',
  heavysnowshowersandthunder_day: 'Heavy Snow Showers with Thunder (Day)',
  heavysnowshowersandthunder_night: 'Heavy Snow Showers with Thunder (Night)',
  heavysnowshowersandthunder_polartwilight: 'Heavy Snow Showers with Thunder (Polar Twilight)',
  lightrainandthunder: 'Light Rain with Thunder',
  lightsleetandthunder: 'Light Sleet with Thunder',
  heavysleetandthunder: 'Heavy Sleet with Thunder',
  lightsnowandthunder: 'Light Snow with Thunder',
  heavysnowandthunder: 'Heavy Snow with Thunder',
  lightrainshowers_day: 'Light Rain Showers (Day)',
  lightrainshowers_night: 'Light Rain Showers (Night)',
  lightrainshowers_polartwilight: 'Light Rain Showers (Polar Twilight)',
  heavyrainshowers_day: 'Heavy Rain Showers (Day)',
  heavyrainshowers_night: 'Heavy Rain Showers (Night)',
  heavyrainshowers_polartwilight: 'Heavy Rain Showers (Polar Twilight)',
  lightsleetshowers_day: 'Light Sleet Showers (Day)',
  lightsleetshowers_night: 'Light Sleet Showers (Night)',
  lightsleetshowers_polartwilight: 'Light Sleet Showers (Polar Twilight)',
  heavysleetshowers_day: 'Heavy Sleet Showers (Day)',
  heavysleetshowers_night: 'Heavy Sleet Showers (Night)',
  heavysleetshowers_polartwilight: 'Heavy Sleet Showers (Polar Twilight)',
  lightsnowshowers_day: 'Light Snow Showers (Day)',
  lightsnowshowers_night: 'Light Snow Showers (Night)',
  lightsnowshowers_polartwilight: 'Light Snow Showers (Polar Twilight)',
  heavysnowshowers_day: 'Heavy Snow Showers (Day)',
  heavysnowshowers_night: 'Heavy Snow Showers (Night)',
  heavysnowshowers_polartwilight: 'Heavy Snow Showers (Polar Twilight)',
  lightrain: 'Light Rain',
  lightsleet: 'Light Sleet',
  heavysleet: 'Heavy Sleet',
  lightsnow: 'Light Snow',
  heavysnow: 'Heavy Snow',
};

export function getReadableWeatherDescription(symbolCode: string): string {
  return weatherDescription[symbolCode] ?? 'Unknown Weather Condition';
}
